[package]
name = "lanotify"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
env_logger = "0.11.8"
log = "0.4.28"
serde = { version = "1.0.228", features = ["derive"] }
serde_with = "3.15.1"
toml = "0.9.8"
ureq = "3.1.2"
